export const loremIpsum = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras in nulla sit amet elit auctor interdum. Maecenas ut urna quis sem fermentum rhoncus ac ac quam. Integer leo neque, tincidunt vel tristique nec, vehicula maximus ligula. Vivamus sit amet dapibus risus. Nunc tincidunt nisl sit amet purus fringilla laoreet. Aliquam felis nibh, aliquet vel ex sed, placerat condimentum leo. Mauris at sem felis. Sed laoreet libero purus, ac tempus lorem commodo sed. Donec a finibus tortor. Nunc efficitur turpis ac posuere aliquam. Donec ut ultricies est, vel suscipit erat. Suspendisse sodales, sapien eu rhoncus ornare, ipsum nibh hendrerit magna, ut bibendum risus velit a enim. Quisque purus arcu, dapibus nec pharetra et, feugiat sit amet ante.

Maecenas venenatis dolor non erat elementum, quis suscipit ante lobortis. Ut accumsan, ante non fringilla consequat, lorem ante tristique arcu, nec vulputate erat lorem vel risus. Ut sit amet bibendum mi. Vivamus ultricies lacinia lectus ut rutrum. Maecenas id mi libero. Aliquam ac odio ligula. Nunc mollis imperdiet efficitur. Pellentesque at tortor at lectus blandit porta pellentesque sit amet sem. Etiam id augue eget nisi gravida commodo quis sed lacus. Praesent ultrices pharetra porttitor. Sed euismod feugiat mi, nec laoreet ante mollis a. In vehicula non risus et pretium. Nulla facilisi. Etiam ornare aliquet dignissim. Ut ac nisl sit amet lorem egestas bibendum. Donec rutrum nisl non libero mattis sagittis.

Nulla faucibus, lectus sollicitudin pharetra vulputate, velit velit suscipit dui, non sodales urna odio sit amet nisl. Sed luctus volutpat ligula a eleifend. Maecenas odio diam, pharetra nec lacinia ac, auctor ut libero. Pellentesque augue lectus, ultricies non enim sed, accumsan efficitur turpis. Pellentesque mattis ultricies finibus. Sed leo velit, tempor vel aliquam id, bibendum in arcu. Duis fringilla, massa eu dapibus dapibus, odio enim volutpat diam, a consectetur lorem augue eu ligula. Nulla facilisi. Nam luctus consequat placerat. Duis at lectus ac est aliquet fringilla in non risus. Curabitur ut libero arcu. Vestibulum sit amet lacus sed ante commodo condimentum in ultrices risus. Vestibulum non viverra urna. Nam id pretium turpis.

Pellentesque non sapien ac justo hendrerit aliquam. Sed dignissim, erat eget elementum tristique, mi libero fringilla dui, ac sodales felis orci mollis enim. Vestibulum porttitor est at nisl auctor tempor. Cras et eros eros. In nec nisl non mi porttitor egestas a ut tortor. Sed commodo lorem et sapien ornare finibus. Pellentesque blandit pellentesque felis, vitae scelerisque mi tempus vel. Aenean commodo interdum sem. Nullam vulputate felis sed malesuada tincidunt. Integer egestas, erat nec rutrum sagittis, mauris urna venenatis dui, eu tristique massa est tristique ligula.

Cras nisl velit, pretium at orci nec, dictum mollis quam. Suspendisse sollicitudin arcu at pulvinar facilisis. Vivamus porttitor dignissim lacus vel vestibulum. Sed dapibus tempus sem. Praesent id tristique elit. Fusce sed tellus egestas, aliquam neque sit amet, sollicitudin augue. Proin venenatis eleifend tortor, in cursus leo. Nam vel orci vitae dui consectetur vestibulum. Pellentesque maximus risus et magna scelerisque pretium. Sed fringilla iaculis porttitor. Sed tempor varius lectus, in posuere tellus sodales a. Pellentesque facilisis libero id condimentum sollicitudin. Nullam ullamcorper erat sed feugiat pellentesque.

Curabitur ipsum quam, tempus sed porta aliquet, finibus et mi. In hac habitasse platea dictumst. Ut ligula est, sodales a vestibulum et, auctor a turpis. Sed ultrices metus eu orci congue tempus. Morbi laoreet sem ipsum, sit amet dictum purus iaculis mattis. In nec sapien sed erat maximus dignissim nec ac metus. Vestibulum dictum consequat aliquet. Mauris nec tellus vel libero imperdiet vulputate. Nam arcu dui, pellentesque a tempor id, consequat eu sem.

Donec dignissim ornare erat, vitae volutpat magna faucibus tempor. Sed sed est justo. Aliquam eu molestie est, ut pulvinar massa. Sed a ligula nec elit dictum ornare. Cras nec cursus nisl. Donec id magna at erat elementum vehicula. Nullam erat erat, bibendum quis orci id, consequat interdum nibh.

Quisque tempor ante nec nulla laoreet posuere. Vestibulum placerat erat tortor, in lobortis arcu hendrerit vitae. Nulla vehicula quam gravida egestas fermentum. Sed vulputate sed nisl sit amet suscipit. Suspendisse potenti. Curabitur eu purus congue, imperdiet sapien ut, placerat urna. Nam rutrum luctus ligula ut feugiat. Donec rutrum leo lectus. Cras aliquet, erat ut efficitur blandit, lorem sem fringilla metus, et semper sapien nulla in lacus. Vivamus finibus pharetra finibus. Phasellus quis dapibus erat. Integer maximus massa odio, quis sodales ligula posuere eget. Donec vulputate purus in sagittis pretium.

Aenean condimentum commodo dignissim. Nullam vulputate sit amet dolor vitae sagittis. Nunc sed gravida arcu, a accumsan nisl. Cras sollicitudin sapien a sapien faucibus ornare. Donec ac diam efficitur, feugiat libero vel, faucibus libero. Nunc convallis nunc justo, sed lacinia tellus venenatis in. Fusce sed tortor pellentesque, sodales elit quis, varius augue. Donec sed massa vitae velit elementum mattis. Mauris a nulla at elit faucibus pretium. Donec egestas pulvinar nibh eget sagittis.

Vestibulum sit amet elit fringilla, rhoncus dui sed, semper nibh. Nam hendrerit imperdiet mauris et cursus. Nam quis nisi non mauris condimentum ultrices nec facilisis nisi. Suspendisse eu rhoncus est, laoreet porttitor leo. Morbi ex neque, pretium non mauris nec, tempor porta sem. Nunc orci sem, rhoncus in nisi nec, tempor convallis turpis. Aenean vitae vulputate purus. Nulla aliquam purus id sapien ullamcorper, quis tristique felis cursus. Sed cursus dignissim tempus.

Sed orci lacus, posuere nec nunc a, semper mollis nisl. Nulla non vestibulum sem. Vestibulum eget leo ac orci pharetra eleifend. Sed quis orci purus. Etiam mauris nunc, posuere vitae elit quis, pretium tempus ante. Vestibulum eget luctus massa. Mauris viverra ante ut ligula tempus pulvinar. Praesent cursus lorem justo, sit amet pharetra diam commodo quis. Nulla eget molestie orci, et euismod augue.

Mauris sit amet ligula in magna malesuada molestie. Curabitur quis nibh sit amet turpis ultrices congue. Etiam et vestibulum mi. Aenean volutpat porttitor luctus. Donec condimentum, ex vitae ornare dignissim, augue purus fringilla leo, in porta nisi risus in lacus. Etiam consectetur urna et tortor volutpat malesuada. Pellentesque gravida elit a laoreet laoreet. Sed eu nulla nec est pulvinar pretium a vitae ipsum. Etiam at rutrum magna. Sed pulvinar laoreet lectus, in condimentum dolor blandit eget. Pellentesque sed tempor dui. Vestibulum consectetur magna lacus, vitae hendrerit nisl dapibus vel. Integer ut eleifend purus. Duis sagittis cursus luctus.

Sed volutpat cursus risus ac facilisis. Praesent volutpat varius risus ut tempus. Praesent pharetra felis ipsum, eu condimentum purus lobortis vitae. Quisque at magna nec ex eleifend varius. Quisque et pharetra lectus. Vivamus congue libero nec libero condimentum congue. Curabitur maximus sodales eleifend. Fusce at lacinia arcu. Suspendisse laoreet vestibulum justo imperdiet pellentesque. Quisque mattis consectetur est.

Maecenas non massa efficitur, facilisis lectus id, mattis turpis. Sed mattis lorem et tortor viverra iaculis. Mauris leo augue, maximus nec turpis in, commodo interdum odio. Aenean eget sagittis tortor. Aliquam fermentum, odio vel dictum tempor, magna est commodo risus, nec posuere orci odio sed eros. Proin urna dui, luctus et gravida nec, consequat eu sem. Quisque egestas quam id lectus vestibulum maximus.

Duis sit amet luctus augue. Maecenas in enim eget diam tristique pretium vel et odio. In cursus, diam in volutpat porta, ex erat scelerisque turpis, ut elementum felis ante pharetra neque. Duis in massa sit amet est consequat accumsan a ut ex. Pellentesque dignissim efficitur quam eu ultricies. Cras vitae condimentum lectus. Suspendisse id erat fermentum, lacinia risus eget, dignissim sem. Donec in lorem consequat, molestie enim et, lobortis nibh. Aliquam erat volutpat. Fusce tristique facilisis felis, et scelerisque diam vestibulum eu.

Phasellus ut elementum eros. Nunc posuere vehicula leo. Etiam gravida risus et diam molestie, in lacinia elit cursus. Donec tempus massa quis sollicitudin maximus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse potenti. Pellentesque consequat magna sit amet nisl tincidunt fermentum. Proin id hendrerit nisi. Mauris nec finibus orci. Phasellus semper non felis vel bibendum. Aliquam venenatis metus leo, vitae suscipit purus cursus ut. Aenean sed elit dapibus purus malesuada consequat. In nunc nisi, cursus id libero eget, lobortis bibendum ipsum.

Duis facilisis, mauris accumsan suscipit porttitor, nisl velit dignissim orci, et malesuada turpis augue in neque. Vivamus fringilla tincidunt accumsan. Pellentesque eu ultrices felis, ac sollicitudin turpis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Maecenas sollicitudin molestie neque, vitae iaculis ante accumsan ut. Nunc accumsan quis eros eu maximus. Donec vel venenatis metus. Donec gravida id leo ut finibus. Suspendisse dictum volutpat quam quis commodo. Sed viverra ullamcorper molestie.

Cras tincidunt felis sit amet placerat molestie. Etiam bibendum nunc semper suscipit interdum. Nam lacinia ligula vitae vulputate vulputate. Cras efficitur augue vitae aliquam tristique. Morbi convallis placerat odio sit amet vulputate. Integer ultrices orci eget condimentum scelerisque. Mauris nisl purus, viverra id magna suscipit, congue commodo orci. Ut mauris ante, laoreet in mauris eget, aliquam feugiat nisl. Aliquam tincidunt auctor ipsum a luctus. Etiam laoreet tortor sit amet tortor lobortis sollicitudin. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque volutpat metus urna, sagittis ullamcorper nulla finibus eget.

Nullam velit justo, porttitor a pharetra interdum, imperdiet eget ipsum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Phasellus accumsan ut ante vel feugiat. Ut in mi orci. Phasellus eu est ut purus egestas iaculis sed et augue. Integer justo orci, dignissim a posuere nec, hendrerit vitae felis. Mauris auctor enim libero, eu cursus augue facilisis id. Aenean dapibus mi vitae magna commodo lobortis.

In auctor convallis massa a eleifend. Nulla convallis pellentesque eros. Mauris tempus, lacus et suscipit facilisis, quam tellus dignissim sapien, at vehicula eros felis a purus. Duis a diam at nibh consequat faucibus. Mauris nec velit sed arcu auctor mattis. Sed sed malesuada risus. Quisque molestie lectus eu fringilla tincidunt. Praesent maximus, orci pretium pulvinar tristique, ipsum nulla pellentesque dolor, et aliquam urna ligula nec ante. Vivamus nisl diam, consequat vitae placerat sit amet, feugiat ut erat. Nam in dolor vel arcu euismod dignissim vitae non elit.`;
  